### ISSUE TITLE
@custom-media being stripped from compiled CSS

### ISSUE THREAD

**Issue by spacedawwwg** [coopdigital/foundations-vars#1]
As you can see in the image, the `@custom-media` declarations are being stripped, meaning they can't be used when the CSS is directly imported.

![image](https://user-images.githubusercontent.com/1691867/58558344-70837480-8218-11e9-80f3-358830978cc6.png)

**Comment by spacedawwwg** [comment]
After looking into this, it seems PostCSS strips the `@custom-media` after being processed.

My suggestion would be to not use PostCSS on this file. Instead, simply have a CSS file with the variables in that can be consumed and compiled once included in a project?

**Comment by matthewmorek** [comment]
CSS vars cannot be used within `@media` declarations, which is why PostCSS with the plugins stack that we use feeds `@custom-media` to build `@media` declarations with these variables, and it doesn't output them as standalone `@custom-media` refs, since there's no use for them outside of PostCSS scope.

Please, note that `foundations-vars` aren't meant to be used outside of PostCSS stacks when building media queries. Please see this for reference: https://github.com/csstools/postcss-preset-env

**Comment by TomSinclair** [comment]
Just to note, I found [postcss-custom-media](https://github.com/postcss/postcss-custom-media) fixes this problem and allows variables to be used inside media queries.
